# Generated by Django 2.2.6 on 2020-01-19 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200119_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 20, 22, 51, 357689, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 20, 22, 51, 357787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 20, 22, 51, 358321, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 20, 22, 51, 358426, tzinfo=utc)),
        ),
    ]
