# Generated by Django 2.1.5 on 2019-02-06 15:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.IntegerField(auto_created=True, blank=True)),
                ('height', models.IntegerField(auto_created=True, blank=True)),
                ('block_index', models.IntegerField(auto_created=True, blank=True)),
                ('size', models.IntegerField(auto_created=True, blank=True)),
                ('n_tx', models.IntegerField(auto_created=True, blank=True)),
                ('nonce', models.IntegerField(auto_created=True, blank=True)),
                ('fee', models.IntegerField(auto_created=True, blank=True)),
                ('bits', models.IntegerField(auto_created=True, blank=True)),
                ('time', models.IntegerField(auto_created=True, blank=True)),
                ('hash', models.CharField(blank=True, max_length=255)),
                ('previous_block', models.CharField(blank=True, max_length=255)),
                ('merkle_root', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(auto_created=True, blank=True)),
                ('type', models.IntegerField(auto_created=True, blank=True)),
                ('tx_index', models.IntegerField(auto_created=True, blank=True)),
                ('value', models.IntegerField(auto_created=True, blank=True)),
                ('n', models.IntegerField(auto_created=True, blank=True)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('script', models.TextField(blank=True, max_length=255)),
                ('script_sig', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_index', models.IntegerField(auto_created=True, blank=True)),
                ('value', models.IntegerField(auto_created=True, blank=True)),
                ('n', models.IntegerField(auto_created=True, blank=True)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('script', models.TextField(blank=True, max_length=255)),
                ('spent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(auto_created=True, blank=True)),
                ('version', models.IntegerField(auto_created=True, blank=True)),
                ('tx_index', models.IntegerField(auto_created=True, blank=True)),
                ('time', models.IntegerField(auto_created=True, blank=True)),
                ('block_height', models.IntegerField(auto_created=True, blank=True)),
                ('double_spend', models.BooleanField()),
                ('relayed_by', models.TextField(blank=True, max_length=255)),
                ('hash', models.TextField(blank=True, max_length=255)),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('outputs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
    ]
