# Generated by Django 2.1.5 on 2019-02-16 14:17

import blockchain.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('height', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('block_index', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('size', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('n_tx', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('nonce', models.CharField(auto_created=True, blank=True, max_length=255, null=True)),
                ('fee', models.BigIntegerField(auto_created=True, blank=True, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('hash', models.CharField(blank=True, default=blockchain.models.create_hash, max_length=255, null=True)),
                ('previous_block', models.CharField(blank=True, max_length=255, null=True)),
                ('merkle_root', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(auto_created=True, blank=True)),
                ('type', models.IntegerField(auto_created=True, blank=True)),
                ('tx_index', models.IntegerField(auto_created=True, blank=True)),
                ('value', models.IntegerField(auto_created=True, blank=True)),
                ('n', models.IntegerField(auto_created=True, blank=True)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('script', models.TextField(blank=True, max_length=255)),
                ('script_sig', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_index', models.IntegerField(auto_created=True, blank=True)),
                ('value', models.IntegerField(auto_created=True, blank=True)),
                ('n', models.IntegerField(auto_created=True, blank=True)),
                ('address', models.TextField(blank=True, max_length=255)),
                ('script', models.TextField(blank=True, max_length=255)),
                ('spent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasPrice', models.BigIntegerField(auto_created=True, blank=True)),
                ('gas', models.BigIntegerField(auto_created=True, blank=True)),
                ('value', models.BigIntegerField(auto_created=True, blank=True)),
                ('time', models.BigIntegerField(auto_created=True, blank=True)),
                ('tx_index', models.BigIntegerField(auto_created=True, blank=True)),
                ('blockNumber', models.BigIntegerField(auto_created=True, blank=True)),
                ('nonce', models.CharField(auto_created=True, blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('hash', models.TextField(blank=True, default=blockchain.models.create_hash, max_length=255, null=True)),
                ('blockHash', models.TextField(blank=True, max_length=255, null=True)),
                ('belonging_to', models.TextField(blank=True, max_length=255)),
                ('relayed_by', models.TextField(blank=True, max_length=255)),
                ('inputs', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='output',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.Transaction'),
        ),
        migrations.AddField(
            model_name='input',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.Transaction'),
        ),
    ]
