# Generated by Django 2.1.7 on 2019-03-15 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 45, 15, 451734, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 45, 15, 451880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 45, 15, 452935, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 15, 7, 45, 15, 453097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(auto_created=True, blank=True, max_length=255, null=True),
        ),
    ]
