# Generated by Django 2.2.1 on 2019-06-06 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='input',
            name='n',
        ),
        migrations.RemoveField(
            model_name='input',
            name='script',
        ),
        migrations.RemoveField(
            model_name='input',
            name='script_sig',
        ),
        migrations.RemoveField(
            model_name='input',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='input',
            name='type',
        ),
        migrations.RemoveField(
            model_name='input',
            name='value',
        ),
        migrations.RemoveField(
            model_name='output',
            name='address',
        ),
        migrations.RemoveField(
            model_name='output',
            name='n',
        ),
        migrations.RemoveField(
            model_name='output',
            name='script',
        ),
        migrations.RemoveField(
            model_name='output',
            name='spent',
        ),
        migrations.RemoveField(
            model_name='output',
            name='tx_index',
        ),
        migrations.AddField(
            model_name='block',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='difficulty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.BigIntegerField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='outputs',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 17, 36, 33, 882219, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 17, 36, 33, 882311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='input',
            name='tx_index',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='output',
            name='value',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 17, 36, 33, 882807, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 17, 36, 33, 882920, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(auto_created=True, blank=True, max_length=255, null=True),
        ),
    ]
