# Generated by Django 2.1.7 on 2019-02-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='blockHash',
            new_name='block_hash',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='blockNumber',
            new_name='block_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='gasPrice',
            new_name='gas_price',
        ),
    ]
