# Generated by Django 2.1.7 on 2019-02-16 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20190216_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
