# Generated by Django 2.1.5 on 2019-02-06 22:44

import blockchain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20190206_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(blank=True, default=blockchain.models.create_hash, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='merkle_root',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
