# Generated by Django 2.2.1 on 2019-06-07 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_auto_20190606_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 34, 40, 526464, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 34, 40, 526556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 34, 40, 527050, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 9, 34, 40, 527163, tzinfo=utc)),
        ),
    ]
