# Generated by Django 2.2.1 on 2019-06-07 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_auto_20190607_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='id_input',
            field=models.BigIntegerField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='id_output',
            field=models.BigIntegerField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 17, 37, 48, 58883, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 17, 37, 48, 58975, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 17, 37, 48, 59474, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 7, 17, 37, 48, 59584, tzinfo=utc)),
        ),
    ]
